server:
  port: 9000
spring:
  application:
    name: eli-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bilibili-Eli/ConfigRepository
          username: bilibili-Eli
          password: Lovery0528
        # svn配置
        # svn:
        #   uri: http://svnhost:port/svn/app-config # SVN仓库地址
        #   username: svnuser # SVN账号(如果没有权限可为空)
        #   password: svnpassword#SVN密码(如果没有权限可为空)
        #   default-label: trunk # 默认SVN分支
        # 本地文件配置
        # native:
        #   search-locations: classpath:/configs #配置文件存放的目录
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7070/eureka/

